name: mon_app
description: "Application collecte prospects"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  connectivity_plus: ^6.0.3
  provider: ^6.1.2
  intl: ^0.19.0
  dropdown_button2: ^2.3.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_uimm.jpg
